name: Build and test ExpenseCalculator
on:
  push:
    paths:
      - ExpenseCalculator/**
      - .github/workflows/ExpenseCalculator.yaml
  workflow_dispatch:
permissions:
  packages: read
jobs:
  build-and-test:
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-build-and-test.yaml@main
    with:
      solution-directory: ExpenseCalculator
      runs-on: windows-latest
